### ISSUE TITLE
Compiler requires `'static` when using transactions on generic AsyncConnection

### ISSUE THREAD

**Issue by kmdreko** [weiznich/diesel_async#104]
The following reproducible sample triggers a compiler error:

```
[dependencies]
diesel = { version = "2.1.1", features = ["postgres"] }
diesel-async = { version = "0.4.1", features = ["postgres", "bb8"] }
```

```
use diesel::pg::Pg;
use diesel::result::Error;
use diesel_async::scoped_futures::ScopedFutureExt;
use diesel_async::{AsyncConnection, RunQueryDsl};

pub async fn demo<T: AsyncConnection<Backend = Pg>>(conn: &mut T) -> Result<(), Error> {
    conn.transaction::<(), Error, _>(|conn| async {
            diesel::sql_query("insert into posts (title, body) values ('title', 'body')").execute(conn).await?;
            Ok(())
        }.scope_boxed()).await?;
    Ok(())
}
```

```
error[E0310]: the parameter type `T` may not live long enough
  --> src/main.rs:7:45
   |
7  |       conn.transaction::<(), Error, _>(|conn| async {
   |  _____________________________________________^
8  | |             diesel::sql_query("insert into posts (title, body) values ('title', 'body')").execute(conn).await?;
9  | |             Ok(())
10 | |         }.scope_boxed()).await?;
   | |_______________________^ ...so that the type `T` will meet its required lifetime bounds
   |
help: consider adding an explicit lifetime bound...
   |
6  | pub async fn demo<T: AsyncConnection<Backend = Pg> + 'static>(conn: &mut T) -> Result<(), Error> {
   |                                                    +++++++++
```

- [x] I have already looked over the [issue tracker](https://github.com/weiznich/diesel_async/issues) for similar possible closed issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

---

As far as I know, using `.transaction()` and `.execute()` in this way should not require a `'static` bound.

I ended up investigating myself, created [a StackOverflow post](https://stackoverflow.com/questions/77034609/why-does-this-combination-of-gats-lifetimes-and-async-require-t-static) about it when I thought I was stuck, and ended up self-answering it as an odd interaction with GATs and `Self`-bounds.

While this isn't a major roadblock for using diesel-async (since workarounds exist) it would be nice to avoid this problem. The solution is to avoid `where Self: 'conn` on the associated types of `AsyncConnection`. This can be done (though a bit of a hack) via a dummy function as shown [in this comment](https://github.com/rust-lang/rust/issues/87479#issuecomment-1478420322). I was able to modify diesel-async with this change and tested it myself. It does fix the above error and I didn't see any conflicts or downsides.

So let me know if that's worth a PR. Or if that doesn't sound worth it or would be problematic, that's fine too.

**Comment by weiznich** [comment]
I would be open for such a change. I cannot promise to merge without having looked at the changes in detail, but given that what's pointed out in the linked issue it should be ok. Try to include at least one test in the PR
