### ISSUE TITLE
r2d2 not supported with AsyncPgConnection

### ISSUE THREAD

**Issue by banool** [weiznich/diesel_async#117]
### Versions

- **Rust:** 1.71.1
- **Diesel:** 2.1.1
- **Diesel_async:** 0.4.1
- **Database:** Postgres
- **Operating System** MacOS 14

### Feature Flags

- **diesel:** postgres_backend, r2d2, serde_json, numeric, chrono
- **diesel_async:** postgres, r2d2, tokio

## Problem Description
With these imports:
```
use diesel::{
    pg::Pg,
    query_builder::{AstPass, Query, QueryFragment},
    r2d2::{ConnectionManager, PoolError, PooledConnection},
    QueryResult, RunQueryDsl,
};
use diesel_async::{AsyncPgConnection};
```

I have these types:
```
pub type PgPool = diesel::r2d2::Pool<ConnectionManager<MyDbConnection>>;
pub type PgDbPool = Arc<PgPool>;
pub type MyDbConnection = AsyncPgConnection;
pub type PgPoolConnection = PooledConnection<ConnectionManager<MyDbConnection>>;
```

Unfortunately, this function results in a compilation error:
```
pub fn new_db_pool(database_url: &str) -> Result<PgDbPool, PoolError> {
    let manager = ConnectionManager::<MyDbConnection>::new(database_url);
    PgPool::builder().build(manager).map(Arc::new)
}
```

The error:
```
the trait bound `AsyncPgConnection: R2D2Connection` is not satisfied
```

With this type instead:
```
pub type PgPool = diesel::r2d2::Pool<AsyncDieselConnectionManager<MyDbConnection>>;
```

You get this error:
```
the trait bound `AsyncDieselConnectionManager<AsyncPgConnection>: ManageConnection` is not satisfied
```

### What are you trying to accomplish?
Use r2d2 with diesel-async. There is an r2d2 feature so you'd think it would work but it doesn't seem to. I imagine we need an r2d2 entry in src/pool_connection/.

### What is the expected output?
The code should compile an work happily.

### What is the actual output?
The compilation error above.

### Are you seeing any additional errors?
N/A

### Steps to reproduce
```
git clone git@github.com:aptos-labs/aptos-indexer-processors.git
git checkout c8188670b64b3733126ac4d0f6fa54bbffb655d1
cd rust
cargo build -p processor
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/weiznich/diesel_async/issues) for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by banool** [comment]
I suppose this is because r2d2 isn't really designed for async connections. You can see an attempt here: https://github.com/weiznich/diesel_async/commit/b9fd59cde1d28f0a57da76272581c4c1a922feed.

But you end up hitting this error:
```
$ cargo build --features r2d2
   Compiling diesel-async v0.4.1 (/Users/dport/github/diesel_async)
error[E0728]: `await` is only allowed inside `async` functions and blocks
  --> src/pooled_connection/r2d2.rs:67:14
   |
65 | /     fn connect(&self) -> Result<Self::Connection, Self::Error> {
66 | |         (self.manager_config.custom_setup)(&self.connection_url)
67 | |             .await
   | |              ^^^^^ only allowed inside `async` functions and blocks
68 | |             .map_err(PoolError::ConnectionError)
69 | |     }
   | |_____- this is not `async`

error[E0728]: `await` is only allowed inside `async` functions and blocks
  --> src/pooled_connection/r2d2.rs:73:14
   |
71 | /     fn is_valid(&self, conn: &mut Self::Connection) -> Result<(), Self::Error> {
72 | |         conn.ping(&self.manager_config.recycling_method)
73 | |             .await
   | |              ^^^^^ only allowed inside `async` functions and blocks
74 | |             .map_err(PoolError::QueryError)
75 | |     }
   | |_____- this is not `async`

For more information about this error, try `rustc --explain E0728`.
error: could not compile `diesel-async` (lib) due to 2 previous errors
```

Either you'd have to make non async implementations of these functions inside AsyncDieselConnectionManager (in which case it's not really async) or use tokio::block_on internally.

**Comment by weiznich** [comment]
Essentially a duplicate of https://github.com/weiznich/diesel_async/discussions/113
