### ISSUE TITLE
Unable to specify the type for sqlite pool

### ISSUE THREAD

**Issue by pickfire** [weiznich/diesel_async#178]
### Versions

- **Rust:** rustc 1.80.0 (051478957 2024-07-21)
- **Diesel:** 2.2.0
- **Diesel_async:** 0.5
- **Database:** sqlite
- **Operating System** `Linux mi 6.10.3-zen1-2-zen #1 ZEN SMP PREEMPT_DYNAMIC Tue, 06 Aug 2024 07:47:21 +0000 x86_64 GNU/Linux (arch)`

### Feature Flags

- **diesel:** chrono, returning_clauses_for_sqlite_3_35
- **diesel_async:** sync-connection-wrapper, async-connection-wrapper, sqlite, deadpool

## Problem Description

Unable to write out the type for sqlite pooled connection.

### What are you trying to accomplish?

Using pooled connection for teloxide, it does dependency injection based on type, however I am unable to explicitly put out the type `Pool<AsyncDieselConnectionManager<SyncConnectionWrapper<SqliteConnection>>>`. The inferred type from rust-analyzer

![image](https://github.com/user-attachments/assets/6d2c4cac-5078-4e47-b3a1-4b83a5a5b09a)

### What is the expected output?

The inferred type should be usable when explicitly typed down.

```rust
let _pool: Pool<AsyncDieselConnectionManager<SyncConnectionWrapper<SqliteConnection>>> = Pool::builder(config).build().unwrap();
```

### What is the actual output?

![image](https://github.com/user-attachments/assets/3e62cf18-09c1-48ef-9b3b-65543f4e965a)

### Are you seeing any additional errors?

<details><summary>errors</summary>

```
error[E0277]: the trait bound `AsyncDieselConnectionManager<SyncConnectionWrapper<SqliteConnection>>: PoolableConnection` is not satisfied
   --> src/main.rs:14:16
    |
14  |     let _pool: Pool<AsyncDieselConnectionManager<SyncConnectionWrapper<SqliteConnection>>> = Pool::builder(co...
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `PoolableConnection` is not implemented for `AsyncDieselConnectionManager<SyncConnectionWrapper<SqliteConnection>>`, which is required by `AsyncDieselConnectionManager<AsyncDieselConnectionManager<SyncConnectionWrapper<SqliteConnection>>>: deadpool::managed::Manager`
    |
    = help: the trait `PoolableConnection` is implemented for `SyncConnectionWrapper<C>`
    = note: required for `AsyncDieselConnectionManager<AsyncDieselConnectionManager<SyncConnectionWrapper<SqliteConnection>>>` to implement `deadpool::managed::Manager`
note: required by a bound in `deadpool::managed::Pool`
   --> /home/ivan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deadpool-0.12.1/src/managed/mod.rs:249:20
    |
249 | pub struct Pool<M: Manager, W: From<Object<M>> = Object<M>> {
    |                    ^^^^^^^ required by this bound in `Pool`

error[E0277]: the trait bound `AsyncDieselConnectionManager<SyncConnectionWrapper<SqliteConnection>>: DerefMut` is not satisfied
   --> src/main.rs:14:16
    |
14  |     let _pool: Pool<AsyncDieselConnectionManager<SyncConnectionWrapper<SqliteConnection>>> = Pool::builder(co...
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `DerefMut` is not implemented for `AsyncDieselConnectionManager<SyncConnectionWrapper<SqliteConnection>>`, which is required by `AsyncDieselConnectionManager<AsyncDieselConnectionManager<SyncConnectionWrapper<SqliteConnection>>>: deadpool::managed::Manager`
    |
    = help: the trait `deadpool::managed::Manager` is implemented for `AsyncDieselConnectionManager<C>`
    = note: required for `AsyncDieselConnectionManager<SyncConnectionWrapper<SqliteConnection>>` to implement `AsyncConnection`
    = note: required for `AsyncDieselConnectionManager<AsyncDieselConnectionManager<SyncConnectionWrapper<SqliteConnection>>>` to implement `deadpool::managed::Manager`
note: required by a bound in `deadpool::managed::Pool`
   --> /home/ivan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deadpool-0.12.1/src/managed/mod.rs:249:20
    |
249 | pub struct Pool<M: Manager, W: From<Object<M>> = Object<M>> {
    |                    ^^^^^^^ required by this bound in `Pool`

error[E0308]: mismatched types
  --> src/main.rs:14:94
   |
14 | ...l: Pool<AsyncDieselConnectionManager<SyncConnectionWrapper<SqliteConnection>>> = Pool::builder(config).build().unwrap...
   |       ---------------------------------------------------------------------------   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `AsyncDieselConnectionManager<SyncConnectionWrapper<...>>`, found `SyncConnectionWrapper<SqliteConnection>`
   |       |
   |       expected due to this
   |
   = note: expected struct `Pool<AsyncDieselConnectionManager<AsyncDieselConnectionManager<...>>>`
              found struct `deadpool::managed::Pool<AsyncDieselConnectionManager<SyncConnectionWrapper<SqliteConnection>>>`
   = note: the full type name has been written to '/home/ivan/src/pickfire/rs/diesel-async-pool/target/debug/deps/diesel_async_pool-d703ecf4a14c8b60.long-type-12503167683362586601.txt'
   = note: consider using `--verbose` to print the full type name to the console

Some errors have detailed explanations: E0277, E0308.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `diesel-async-pool` (bin "diesel-async-pool") due to 3 previous errors
```
</details>

### Steps to reproduce

1. `cargo new diesel-async-pool`
2. Add the following code

<details><summary>src/main.rs</summary>

```rust
use diesel::sqlite::SqliteConnection;
use diesel_async::pooled_connection::deadpool::Pool;
use diesel_async::pooled_connection::AsyncDieselConnectionManager;
use diesel_async::sync_connection_wrapper::SyncConnectionWrapper;

#[tokio::main]
async fn main() {
    let db_url = std::env::var("DATABASE_URL").expect("Env var `DATABASE_URL` not set");

    let config =
        AsyncDieselConnectionManager::<SyncConnectionWrapper<SqliteConnection>>::new(db_url);
    let _pool = Pool::builder(config).build().unwrap();
    // putting the type fails
    let _pool: Pool<AsyncDieselConnectionManager<SyncConnectionWrapper<SqliteConnection>>> = Pool::builder(config).build().unwrap();
}
```
</details>

<details><summary>Cargo.toml</summary>

```toml
[package]
name = "diesel-async-pool"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.28.2", default-features = false, features = ["macros", "rt-multi-thread", "sync"] }
diesel = { version = "2.2.0", default-features = false, features = ["chrono", "returning_clauses_for_sqlite_3_35"] }
diesel-async = { version = "0.5", features = ["sync-connection-wrapper", "async-connection-wrapper", "sqlite", "deadpool"] }
```
</details>

3. Run `cargo check`

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/weiznich/diesel_async/issues) for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment]
This is expected behaviour as you mixed up the pool types. `deadpool` advises that crates implementing the necessary pool traits provide an reexported pool type that already contains the right connection manager. That makes `diesel_async::pooled_connection::deadpool::Pool<SyncConnectionWrapper<SqliteConnection>>` the correct type in this location.

This can be seen in the error message that mentions double nested `AsyncConnectionManager` constructs and in [the documentation of the `Pool`](https://docs.rs/diesel-async/latest/diesel_async/pooled_connection/deadpool/type.Pool.html) type.

I know that quite a few people seem to struggle with this behavior, but given that this is what upstream documents (by recommending using [this macro](https://docs.rs/deadpool/latest/deadpool/macro.managed_reexports.html)) that downstream providers should do I'm not sure how to address that in a better way.

(Leaving this open for now, as we certainly need to find some way to address this in the documentation)

**Comment by pickfire** [comment]
Not sure if we should create an issue in deadpool too but cc @bikeshedder for visibility.

**Comment by bikeshedder** [comment]
What's the issue with the `managed_reexports` macro?

The reason for it to exist were constant mixups in the `deadpool-*` crates where I made a "small" type errors. With the macros it's basically impossible to mess up the reexports and they're guaranteed to be consistent for all `deadpool-*` crates.

**Comment by bikeshedder** [comment]
Just wanted to add. You're of course free to not use this macro. It's merely a convenience tool and part of the public API which makes writing deadpool powered pool implementations easier and more consistent.

**Comment by weiznich** [comment]
> What's the issue with the managed_reexports macro?

The "problem" here is that the `managed_reexports` macro [encourages](https://docs.rs/deadpool/latest/src/deadpool/managed/reexports.rs.html#31) reexporting a `Pool` type with the manager type already filled in. For diesel-async I followed that pattern, but as the manager itself is generic over the connection type users still end up with a `Pool<T>` type, and some of the users seem to miss the difference between `deadpool::Pool` and `diesel_async::pooled_connection::deadpool::Pool`, which results in a duplicated `AsyncConnectionManager` in the type, which in turn is problematic. Maybe better documentation can solve this, maybe it requires some additional changes.

> Just wanted to add. You're of course free to not use this macro. It's merely a convenience tool and part of the public API which makes writing deadpool powered pool implementations easier and more consistent.

I could, but it would make the API inconsistent with the other deadpool crates.

**Comment by bikeshedder** [comment]
How about creating separate modules that contain the reexports for each connection type? That's exactly what I did in `deadpool-diesel`. e.g. https://github.com/bikeshedder/deadpool/blob/master/diesel/src/postgres.rs

It's rare that one wants to target multiple databases in a single code base and those could still use the generic `Pool<T>`.

**Comment by weiznich** [comment]
That would be a possibility for the built-in connection types, but I would prefer to keep things in such a way that third party connection types can get the same level of integration as the first party ones.
