### ISSUE TITLE
Cannot Run Migrations because Connection is required to live Forever

### ISSUE THREAD

**Issue by xFGhoul** [weiznich/diesel_async#205]
### Versions

- **Rust:** 1.83
- **Diesel:** 2.2.6
- **Diesel_async:** 0.5.2
- **Database:** PostgreSQL
- **Operating System** Windows 11

### Feature Flags

- **diesel:** `postgres`, `r2d2`
- **diesel_async:** `postgres`, `bb8`

## Problem Description
I am trying to run my migrations in my connect function of my app, but I cannot seem to pass `pool` to `run_pending_migrations` because it requires the `pool`, and henceforth `connection` to live forever, but it will be freed after `run_pending_migrations` is done.

### What are you trying to accomplish?
Run Migrations in `establish_connection` :
```rust
pub async fn establish_connection() -> Result<DatabasePool, Box<dyn std::error::Error>> {
    // -- Load .env
    dotenv().ok();

    // -- Get Database URL
    let database_uri = env::var("DATABASE_URI").expect("[!] DATABASE_URI Environment Variable Must Be Set");

    // -- Create Manager
    let manager = AsyncDieselConnectionManager::<AsyncPgConnection>::new(database_uri);

    // -- Create Database Pool
    let pool = Pool::builder()
        .max_size(10)
        .build(manager)
        .await
        .expect("[!] Could Not Create Database Pool");

    // -- Define Migrations
    pub const MIGRATIONS: EmbeddedMigrations = embed_migrations!("migrations");

    // -- Get Database Connection
    let mut connection = pool.clone().get().await.ok().unwrap();

    // -- Run Migrations
    MIGRATIONS
        .run_pending_migrations(&mut connection)
        .await
        .map_err(|err| anyhow!("[!] Error Running Database Migrations: {err}"))?;

    // Return Pool
    Ok(pool)
}
```

### What is the expected output?
Migrations are run and app startup is normal

### What is the actual output?
```rust
error[E0716]: temporary value dropped while borrowed
  --> src\db.rs:41:26
   |
41 |     let mut connection = pool.clone().get().await.ok().unwrap();
   |                          ^^^^^^^^^^^^------                    - temporary value is freed at the end of this statement
   |                          |
   |                          creates a temporary value which is freed while still in use
   |                          argument requires that borrow lasts for `'static`
```

### Are you seeing any additional errors?
Not that I have come across yet

### Steps to reproduce
follow my exact setup and course of actions, you can access my repository at https://github.com/TeamHypertrophy/Protein
I will update it shortly.

## Checklist

- [ x] I have already looked over the [issue tracker](https://github.com/weiznich/diesel_async/issues) for similar possible closed issues.
 
- [ x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [ ] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment]
The `run_pending_migrations` method expects a type that essentially implement `diesel::Connection`. That's not the case in your example, therefore the error. See [this example](https://github.com/weiznich/diesel_async/blob/main/examples/postgres/run-pending-migrations-with-rustls/src/main.rs#L20) for how to run migrations with diesel-async. 

As for the error message: That one is really bad, please fill an issue in the rustc issue tracker, as that's the only place where this could realistically be improved.
