### ISSUE TITLE
diesel-async with a connection pool: the trait `Connection` is not implemented for ....

### ISSUE THREAD

**Issue by dessalines** [weiznich/diesel_async#32]
I'm trying to get diesel-async + bb8 + postgres working, but its not able to convert the pooled connection -> AsyncPgConnection to work with diesel-async. I also can't find any unit tests for any of the connection pools. 

Example:

```rs
use diesel_async::pooled_connection::bb8::Pool;
use diesel_async::pg::AsyncPgConnection;
pub type DbPool = Pool<AsyncPgConnection>;

pub async fn delete_for_community(
  pool: &DbPool,
  for_community_id: CommunityId,
) -> Result<usize, Error> {
  let mut conn = pool.get().await.unwrap();
  diesel::delete(community_moderator.filter(community_id.eq(for_community_id))).execute(&mut conn); // <--- Error here
}
```

Error:

```
diesel::delete(community_moderator.filter(community_id.eq(for_community_id))).execute(&mut conn);          |                                                                                           ^^^^^^^ the trait
`Connection` is not implemented for `bb8::api::PooledConnection<'_, AsyncDieselConnectionManager<AsyncPgConnection>>`               |                                                                                                                        =
help: the following other types implement trait `Connection`:                                                                    PooledConnection<M>                                                                                                      diesel::PgConnection

note: required because of the requirements on the impl of `diesel::query_dsl::methods::ExecuteDsl<bb8::api::PooledConnection<'_, AsyncDieselConnectionManager<AsyncPgConnection>>, Pg>` for `DeleteStatement<schema::community_moderator::table, query_builder::where_clause::WhereClause<diesel::expression::grouped::Grouped<diesel::expression::operators::Eq<schema::community_moderator::columns::community_id, diesel::expression::bound::Bound<diesel::sql_types::Integer, i32>>>>>`  note: required by a bound in `diesel::RunQueryDsl::execute`                                                                  --> /home/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel-2.0.0/src/query_dsl/mod.rs:1401:15                 |                                                                                                                   1401 |         Self: methods::ExecuteDsl<Conn>,                                                                               |               ^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `diesel::RunQueryDsl::execute`
```

**Comment by weiznich** [comment]
That's surprising as there is a doc-test for exactly this case [here](https://github.com/weiznich/diesel_async/blob/96688d476c6c160dce51b3a643e6ed90a953f6bb/src/pooled_connection/bb8.rs#L3-L42) and that test is running (and passing) in the CI setup. 

Can you provide a minimal reproducible example for this, including the relevant `Cargo.toml` + `Cargo.lock` file.

**Comment by dessalines** [comment]
```sh
git clone https://github.com/dessalines/diesel-async-bb8-test
cd diesel-async-bb8-test
cargo check
```

**Comment by weiznich** [comment]
This is a user error, as the example imports `diesel::RunQueryDsl` instead of the async counter part `diesel_async::RunQueryDsl`. This is expected as `AsyncConnection`/`diesel_async::RunQueryDsl` belong together in the same way `Connection`/`diesel::RunQueryDsl` belonging together.

For reference the following code compiles for me:
```rust
use diesel_async::pooled_connection::{bb8::Pool, AsyncDieselConnectionManager};
use diesel_async::RunQueryDsl;

use diesel_async::pg::AsyncPgConnection;

diesel::table! {
  person (id) {
    id -> Int4,
    name -> Text,
  }
}

#[tokio::main]
async fn main() {

    let config = AsyncDieselConnectionManager::<AsyncPgConnection>::new("test");
    let pool = Pool::builder().build(config).await.unwrap();
    let mut conn = pool.get().await.unwrap();
    let _output = diesel::delete(person::table).execute(&mut conn).await.unwrap();
}

```

Closed as this is neither an issue in `diesel_async` nor is there anything actionable here (there exists an test-case for this kind of pooled connections + the documentation mentions that users need to use the async counterparts of the relevant traits.)

**Comment by dessalines** [comment]
ooooh okay that wasn't clear I needed to use the diesel_async version of runquerydsl. Could you add that import to this example? I can't find that import anywhere.

https://docs.rs/diesel-async/0.1.0/diesel_async/

**Comment by weiznich** [comment]
It's there on the fourth line of the overall documentation, but I agree that it can be added to some examples as well. 
To explicitly cite the relevant documentation block:

> diesel-async is an extension to diesel itself. It is designed to be used together with the main diesel crate. It only provides async variants of core diesel traits, that perform actual io-work. This includes async counterparts the following traits:
>
> *    [diesel::prelude::RunQueryDsl](https://docs.diesel.rs/2.0.x/diesel/prelude/trait.RunQueryDsl.html) -> [diesel_async::RunQueryDsl](https://docs.rs/diesel-async/0.1.0/diesel_async/trait.RunQueryDsl.html)
> …

**Comment by Christiantyemele** [comment]
Hey guys i cannot use pool_connection from diesel_async, compiler says its not found in the root

**Comment by Christiantyemele** [comment]
i'm trying to use wrapping my AsyncPgConnection in a bb8 Pool , but on calling .get() and .await() on the connection Pool i get the TimedOut error
```rs
pub async fn establish_connection() -> Pool<AsyncPgConnection> {
    dotenv().ok();
    let database_url = env::var("DATABASE_URL").expect("DATABASE_URL must be set");
    let manager = AsyncDieselConnectionManager::<AsyncPgConnection>::new(database_url);

    Pool::builder()
        .build(manager)
        .await
        .expect("Could not build connection pool")
}

pub async fn get_user(pool: &mut Database, usernam: String) -> Vec<Users> {
    use schema::users::dsl::*;
    let mut conn = pool.get().await.unwrap();
    let result = users
        .filter(username.eq(usernam))
        .select(Users::as_select())
        .load(&mut *conn)
        .await
        .unwrap();

```

**Comment by weiznich** [comment]
@Christiantyemele We do not provide support in closed old issues. Please use the [discussion forum](https://github.com/weiznich/diesel_async/discussions) for such support questions. Be sure to provide a minimal reproducible example there.
