### ISSUE TITLE
Relicense the crate under MIT/Apache 2.0

### ISSUE THREAD

**Issue by weiznich** [weiznich/diesel_async#39]
This issue tracks the progress to relicense `diesel_async` from AGPL 3.0 to MIT/Apache 2.0.

I merged contributions from the following people:

- [x] @smklein 
    +  https://github.com/weiznich/diesel_async/pull/8 
- [x] @Razican 
    + https://github.com/weiznich/diesel_async/pull/15
- [ ] @gwy15
    + https://github.com/weiznich/diesel_async/pull/21
- [x] @fluxxu 
    + https://github.com/weiznich/diesel_async/pull/30 (already consent to transfer the ownership of this change to me)
- [x] @johnchildren 
    + https://github.com/weiznich/diesel_async/pull/35 (already consent to transfer the ownership of this change to me)
- [x] @livingcorpse25 
    + https://github.com/weiznich/diesel_async/pull/37 (already consent to transfer the ownership of this change to me)
- [x] @treysidechain 
    + https://github.com/weiznich/diesel_async/pull/38 (already consent to transfer the ownership of this change to me)
- [x] @medcat
    + https://github.com/weiznich/diesel_async/pull/40 (already consent to transfer the ownership of this change to me)

For @smklein, @Razican  and @gwy15: Please comment on this issue whether you agree to relicense your code or not?
For @fluxxu, @johnchildren, @livingcorpse25, @treysidechain: I already checked your boxes above, as you agreed to transfer the ownership of your changes to me. Please comment if you disagree with this change, otherwise I assume your consent.

**Comment by smklein** [comment]
I agree to relicense (and I'll check my own box). Thank you for doing this!

**Comment by Razican** [comment]
I also agree to relicense the code :)
