### ISSUE TITLE
Some backend specific impls in Diesel are unavailable (e.g. InsertOrIgnore)

### ISSUE THREAD

**Issue by oeed** [weiznich/diesel_async#70]
### Versions

- **Rust: 1.67**
- **Diesel: 2.0.3**
- **Diesel_async: 2.0.1**
- **Database: MySQL**
- **Operating System: macOS**

### Feature Flags

- **diesel: _none_**
- **diesel_async:  mysql, deadpool**

## Problem Description

Some query types (haven't researched an exhaustive list) will not currently be usable with diesel_async as upstream diesel keeps their implementation behind the backend features. For example:

```rust
#[cfg(feature = "mysql")]
impl QueryFragment<crate::mysql::Mysql> for InsertOrIgnore {
    fn walk_ast<'b>(
        &'b self,
        mut out: AstPass<'_, 'b, crate::mysql::Mysql>,
    ) -> QueryResult<()> {
        out.push_sql("INSERT IGNORE");
        Ok(())
    }
}
```

As I do not have the `mysql` flag on diesel enabled I cannot use `insert_or_ignore_into`.

I am not sure what the right solution for this is really. I specifically _cannot_ turn on `mysql` on diesel as I explicitly want to avoid the native dependencies it requires. Potentially a separate 'MySQL syntax but not backend' flag on diesel would solve this – albeit it's not the most elegant.

### What are you trying to accomplish?
I am attempting to migrate older sync diesel code, using `insert_or_ignore_into`, to diesel_async. The same query fails to compile when async, while building fine in standard diesel.

```rust
diesel::insert_or_ignore_into(users::table)
    .values((users::id.eq(1), users::name.eq("Jim")))
    .execute(&mut connection)
    .await?;
```

### What is the expected output?
The query compiles and works as intended.

### What is the actual output?

```
the trait `QueryFragment<Mysql>` is not implemented for `query_builder::insert_statement::private::InsertOrIgnore`
```

### Steps to reproduce

```rust
use diesel::prelude::*;
use diesel_async::{RunQueryDsl, AsyncConnection, AsyncMysqlConnection};

table! {
    users {
        id -> Integer,
        name -> Text,
    }
}

// create an async connection
let mut connection = AsyncMysqlConnection::establish(std::env::var("DATABASE_URL")?).await?;

diesel::insert_or_ignore_into(users::table)
    .values((users::id.eq(1), users::name.eq("Jim")))
    .execute(&mut connection)
    .await?;
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/weiznich/diesel_async/issues) for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment]
Thanks for reporting. Thats something that needs to be fixed in diesel itself. The `#[cfg(feature ="mysql")]` needs to be changed to `#[cfg(feature = "mysql_backed")] `. Seems like that instance was missed when I introduced the `mysql_backend` feature there.

**Comment by oeed** [comment]
Oh I wasn't aware a feature was already present, did you want me to open a PR to do so?

**Comment by weiznich** [comment]
That would be great. Otherwise I will deal with that sometimes later this week.
