### ISSUE TITLE
Fail to get the connection with the features ["postgres", "bb8"]

### ISSUE THREAD

**Issue by peng-huang-ch** [weiznich/diesel_async#99]
### Versions

- **Rust:** `rustc 1.72.0`
- **Diesel:** 2.1.0
- **Diesel_async:** 0.3.1
- **Database:** postgres
- **Operating System**  macos 13.4.1 

### Feature Flags

- **diesel:** `["postgres", "r2d2"]`
- **diesel_async:** `["postgres", "bb8"]`

## Problem Description
Fail to get the connection, `TimedOut`

### What are you trying to accomplish?
Manager the connection with the `diesel-async`

### What is the actual output?
```rs
thread 'pg_async::tests::test_init_db' panicked at 'could not get connection: TimedOut', crates/srv-storage/src/pg_async.rs:39:41
stack backtrace:
   0: rust_begin_unwind
             at /rustc/065a1f5df9c2f1d93269e4d25a2acabbddb0db8d/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/065a1f5df9c2f1d93269e4d25a2acabbddb0db8d/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/065a1f5df9c2f1d93269e4d25a2acabbddb0db8d/library/core/src/result.rs:1651:5
   3: core::result::Result<T,E>::expect
             at /rustc/065a1f5df9c2f1d93269e4d25a2acabbddb0db8d/library/core/src/result.rs:1033:23
   4: srv_storage::pg_async::tests::test_init_db::{{closure}}
             at ./src/pg_async.rs:39:24
```

### Are you seeing any additional errors?
No additional error is shown.

### Steps to reproduce

```rs
use diesel_async::{
    pooled_connection::{bb8::Pool, bb8::PooledConnection, AsyncDieselConnectionManager},
    AsyncPgConnection,
};

pub type DbConnectionManger = AsyncDieselConnectionManager<AsyncPgConnection>;

pub type DbPool = Pool<AsyncPgConnection>;

pub type DbConnection<'a> = PooledConnection<'a, AsyncDieselConnectionManager<AsyncPgConnection>>;

#[tracing::instrument()]
pub async fn init_db(database_url: &str) -> DbPool {
    let mgr = AsyncDieselConnectionManager::<AsyncPgConnection>::new(database_url);

    Pool::builder()
        .build(mgr)
        .await
        .expect("could not build connection pool")
}

#[cfg(test)]
mod tests {
    use super::init_db;
    use diesel::{prelude::*, sql_query, sql_types::Text};
    use diesel_async::RunQueryDsl;
    #[derive(QueryableByName)]
    struct SqlVersion {
        #[diesel(sql_type = Text)]
        pub version: String,
    }

    #[tokio::main]
    #[test]
    async fn test_init_db() {
        dotenvy::dotenv().ok();
        let database_url = std::env::var("DATABASE_URL").expect("Expected DATABASE_URL to be set");
        let pool = init_db(database_url.as_str()).await;
        let mut conn = pool.get().await.expect("could not get connection");
        let version = sql_query("SELECT version()")
            .get_result::<SqlVersion>(&mut conn)
            .await;

        assert!(version.is_ok());
        let version = version.unwrap();
        println!("database version {}", version.version);
    }
}

```

```toml
diesel = { version = "2.1.0", features = ["postgres", "r2d2"] }
diesel-async = { version = "0.3.1", features = ["postgres", "bb8"] }
```
## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/weiznich/diesel_async/issues) for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment]
I've tried your minimal example locally and the tests passes for my setup. Additionally [this issue](https://github.com/djc/bb8/issues/141) indicates that this error also might be returned if your connection URL is somehow invalid. I agree that this error message is not optimal, but that's an issue in bb8 then.

Closed that I'm not able to reproduce the issue locally with a valid database URL.

**Comment by peng-huang-ch** [comment]
Thank you for your reply. I don't think it's a URL issue. I have provided a [repo](https://github.com/peng-huang-ch/diesel_async_demo) to reproduce the issue.

<img width="1346" alt="image" src="https://github.com/weiznich/diesel_async/assets/22047020/2084ddf2-9f0e-4eff-b63b-6cb8a230fc81">

**Comment by weiznich** [comment]
I've checked your repo and I cannot reproduce the issue with that either. Both tests complete successful for me. Again I believe that this is just an issue with your database URL. Please note that `diesel::PgConnection` and `diesel_async::AsyncPgConnection` do not necessarily support the same database URL params/format. They are completely different implementations that support a different set of parameters. Just because a database URL works with one of the implementations it does not necessarily mean that it will work with the other implementation as well. Checkout the documentation of both types to learn about the required format.

**Comment by peng-huang-ch** [comment]
Once I change my url format to the `postgres://${whoami}@localhost/signatures`, the test passed.
[The connection URLs should be in the form](https://github.com/weiznich/diesel_async/blob/5ba4375a9c01b7b0be0d18b31085d25439955e57/src/pg/mod.rs#L38) 
Thanks again.
